routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/userDash', 'HomeController@index')->name('home');
Route::get ('/userDash/show_all', 'RecipesController@show_all')->name('recipes.show_all');
Route::post('userDash/recipes/search', 'RecipesController@search')->name('recipes.search');

Route::resource('/userDash/recipes', 'RecipesController');
Route::resource('/userDash/recipes/{recipe}/quantity', 'QuantityController')->except('index');
Route::resource('/userDash/recipes/{recipe}/preparation', 'PreparationController')->except('index');
Route::resource('/userDash/ingredients', 'IngredientsController');

resources/views/inc/footer.blade.php
<!-- Scripts -->
<script src="http://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{{ asset('js/bootstrap.js') }}"></script>
</body>
</html>

resources/views/inc/header.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
</head>
<body>

resources/views/inc/navbarRight.blade.php
<nav class="navbar navbar-light bg-light flex-md-nowrap p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="">My CookBook</a>
        <ul class="nav navbar-right px-3">
                <!-- Authentication Links -->
                @guest
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre style="color: #000">
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                        <a href="{{ route('logout') }}" class="dropdown-item"
                           onclick="event.preventDefault();
                                                            document.getElementById('logout-form').submit();">
                            {{ __('Sign Out') }}
                        </a>
                        <a href="/userDash" class="dropdown-item">Back to Dashboard</a>

                        <form action="{{ route('logout') }}" id="logout-form"  method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
</nav>

resources/views/inc/navbarUser.blade.php
<nav class="navbar navbar-light bg-light flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="">User Dashboard</a>
    <ul class="nav navbar-right px-3">
        <!-- Authentication Links -->
        @guest
            <li><a href="{{ route('login') }}">Login</a></li>
            <li><a href="{{ route('register') }}">Register</a></li>
        @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre style="color: #000">
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                    <a href="{{ route('logout') }}" class="dropdown-item"
                       onclick="event.preventDefault();
                                                            document.getElementById('logout-form').submit();">
                        {{ __('Sign Out') }}
                    </a>

                    <form action="{{ route('logout') }}" id="logout-form"  method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        @endguest
    </ul>
</nav>

resources/views/inc/sidebar.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="/userDash" style="color: #6c757d;">
                    <span class="fas fa-tachometer-alt"></span>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-link" style="color: #6c757d">
                <a href="javascript:;" data-toggle="collapse" data-target="#demo1"  style="color: #6c757d"><span class="far fa-lemon" ></span> Ingredi&euml;nten</a>
                <ul id="demo1" class="collapse">
                    <li>
                        <a href="{{ route('ingredients.index') }}" style="color: #6c757d">Alle Ingredi&euml;nten</a>
                    </li>
                    <li>
                        <a href="{{ route('ingredients.create') }}" style="color: #6c757d">Create</a>
                    </li>
                </ul>
            </li>
            <li class="nav-link">
                <a href="javascript:;" data-toggle="collapse" data-target="#demo" style="color: #6c757d"><span class="fas fa-utensils"></span> Recipes</a>
                <ul id="demo" class="collapse">
                    <li>
                        <a href="{{ route('recipes.show_all') }}" style="color: #6c757d">Alle Recipes</a>
                    </li>
                    <li>
                        <a href="{{ route('recipes.create') }}" style="color: #6c757d">create</a>
                    </li>
                    <li>
                        <a href="{{ route('recipes.index') }}" style="color: #6c757d">Index</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>