routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/userDash', 'HomeController@index')->name('home');
Route::get ('/userDash/show_all', 'RecipesController@show_all')->name('recipes.show_all');
Route::post('userDash/recipes/search', 'RecipesController@search')->name('recipes.search');

Route::resource('/userDash/recipes', 'RecipesController');
Route::resource('/userDash/recipes/{recipe}/quantity', 'QuantityController')->except('index');
Route::resource('/userDash/recipes/{recipe}/preparation', 'PreparationController')->except('index');
Route::resource('/userDash/ingredients', 'IngredientsController');

app/Ingredient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ingredient extends Model
{
    protected $fillable = ['name'];

    public function recipes(){
        return $this->belongsToMany('App\Recipe');
    }

}

app/Http/Controllers/IngredientsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SaveIngredient;
use App\Http\Requests\SaveIngredientRequest;
use App\Ingredient;

use Illuminate\Http\Request;

class IngredientsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ingredients = Ingredient::latest()->paginate(12);
        return view('ingredients.index', compact('ingredients', 'ingredient'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ingredients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveIngredientRequest $request)
    {
        $ingredient = new Ingredient;
        $ingredient->name = $request->input('name');
        $ingredient->save();

        return redirect()->route('ingredients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function show(Ingredient $ingredient)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function edit(Ingredient $ingredient)
    {

        return view('ingredients.edit', compact('ingredient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ingredient = Ingredient::findOrFail($id);
        $ingredient->update($request->only('name'));

        return redirect()->route('ingredients.index', compact('ingredient'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ingredient $ingredient)
    {
        $ingredient->delete();

        return redirect()->route('ingredients.index');
    }
}

resources/views/ingredients/create.blade.php
@extends('layouts.app')

@include('inc.navbarUser')

@section('content')

    @include('inc.sidebar')

    <div class="col col-lg-10 mt-3">
            <form action="{{ route('ingredients.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="col-md-10">
                    <div class="card">
                        <h6 class="card-header text-muted">Nieuw Ingredi&euml;nt</h6>
                        <div class="card-body">
                            <h5 class="card-title">Ingredi&euml;nt naam</h5>
                            <div class="form-group">
                                <input class="form-control" type="text" name="name">
                                @if($errors->has('name'))
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                @endif
                            </div>
                            <button class="btn btn-outline-primary btn-sm" type="submit" name="submit">Create</button>
                        </div>
                    </div>
                </div>
                {{--<div class="form-group">--}}
                    {{--<label for="name">Ingredi&euml;nt naam</label>--}}
                    {{--<input class="form-control" type="text" name="name">--}}
                    {{--@if($errors->has('name'))--}}
                        {{--<span class="text-danger">{{ $errors->first('name') }}</span>--}}
                    {{--@endif--}}
                {{--</div>--}}
                {{--<div class="form-group">--}}
                    {{--<input class="btn btn-primary" type="submit" name="submit" value="create">--}}
                {{--</div>--}}
            </form>
    </div>


@endsection

resources/views/ingredients/edit.blade.php
@extends('layouts.app')

@include('inc.navbarUser')

@section('content')

    @include('inc.sidebar')

    <div class="col col-lg-10">
        <h3 class="mt-5">Nieuw ingredi&euml;nt</h3>
        <div class="col-md-6">
            <form action="{{ route('ingredients.update', $ingredient->id) }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                @method('PUT')
                <div class="col-md-10 mt-5">
                    <div class="card">
                        <h6 class="card-header text-muted">Nieuw Ingredi&euml;nt</h6>
                        <div class="card-body">
                            <h5 class="card-title">Ingredi&euml;nten naam</h5>
                            <input type="text" class="form-control" name="name" value="{{ old('name', $ingredient->name) }}"><br>
                            @if($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                            <button class="btn btn-outline-primary btn-sm" type="submit" name="submit" value="edit ingredient">Edit ingredi&euml;nt</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>


@endsection

resources/views/ingredients/index.blade.php
@extends('layouts.app')

@include('inc.navbarUser')

@section('content')

    @include('inc.sidebar')
    <div class="col col-lg-10 mt-3">
        {{--Add Ingredient--}}
        <h4 class="card-header text-muted">Ingredi&euml;nten toevoegen</h4>
        <table class="table table-sm table-bordered table-hover">
            <thead>
            <tr>
                <th>Id</th>
                <th>Naam</th>
                <th>Created</th>
                <th>Updated</th>
                <th>Controls</th>
            </tr>
            </thead>
            <tbody>
            @foreach($ingredients as $ingredient)
                <tr>
                    <td>{{ $ingredient->id }}</td>
                    <td>{{ $ingredient->name }}</td>
                    <td>{{ $ingredient->created_at }}</td>
                    <td>{{ $ingredient->updated_at }}</td>
                    <td>
                        <form action="{{ route('ingredients.destroy', $ingredient->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <a href="{{ route('ingredients.edit', $ingredient->id) }}" class="btn btn-outline-secondary btn-sm">Edit</a>
                            <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $ingredients->links() }}

        <div class="form-group">
            <a class="btn btn-outline-info" href="{{ route('ingredients.create') }}">Create Ingredi&euml;nt</a>
        </div>
        {{--End add ingredient--}}
    </div>

@endsection