routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/userDash', 'HomeController@index')->name('home');
Route::get ('/userDash/show_all', 'RecipesController@show_all')->name('recipes.show_all');
Route::post('userDash/recipes/search', 'RecipesController@search')->name('recipes.search');

Route::resource('/userDash/recipes', 'RecipesController');
Route::resource('/userDash/recipes/{recipe}/quantity', 'QuantityController')->except('index');
Route::resource('/userDash/recipes/{recipe}/preparation', 'PreparationController')->except('index');
Route::resource('/userDash/ingredients', 'IngredientsController');

app/Recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    public $directory = "/images/";

    protected $fillable = ['name'];

    public function users(){
        return $this->belongsToMany('App\User');
    }

    public function photos(){
        return $this->hasOne('App\Photo');
    }

    public function quantities(){
        return $this->hasMany('App\Quantity');
    }

    public function ingredients(){
        return $this->belongsToMany('App\Ingredient');
    }

    public function preparations(){
        return $this->hasMany('App\Preparation');
    }
}

app/Http/Controllers/RecipesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SaveRecipeRequest;
use App\Ingredient;
use App\Preparation;
use App\Quantity;
use App\User;
use App\Recipe;
use App\Photo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rules\In;

class RecipesController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $recipes = Recipe::orderBy('id', 'desc')->paginate(3);
       // $paginate = Recipe::latest();
        return view('recipes.index', compact('recipes', 'paginate'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ingredients = Ingredient::all();
        return view('recipes.create', compact('ingredients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveRecipeRequest $request)
    {
        $recipe = new Recipe();
        $photo = new Photo();

        $recipe->name = $request->input('name');

        if ($file = $request->file('file')){

            $name = $file->getClientOriginalName();
            $file->move('images', $name);
            $photo->path = $name;
        }

        $recipe->save();
        $recipe->photos()->save($photo);

        $user = Auth::user();
        $user->recipes()->attach($recipe->id);

        return redirect()->route('recipes.edit', $recipe->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //$recipes = Recipe::findOrFail($id);
        $recipe = Auth::user()->recipes->find($id);
        $ingredients = Ingredient::all();
        $preparations = Preparation::all();
        return view('recipes.show', compact( 'recipe', 'ingredients', 'preparations'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $recipe = Recipe::find($id);
        $quantities = $recipe->quantities;
        $preparations = $recipe->preparations;
        $ingredients = Ingredient::all();

        return view('recipes.edit', compact('recipe', 'preparations', 'quantities', 'ingredients' ,'quantity'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $recipe = Recipe::findOrFail($id);

        $recipe->update($request->only('name', 'file', 'preparation'));

        return redirect()->route('recipes.show_all');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $recipe = Recipe::find($id);

        foreach ($recipe->quantities as $quantity){
            $quantity->delete();
        }
        foreach($recipe->preparations as $prep){
            $prep->delete();
        }

        $recipe->photos->delete();

        $recipe->delete();
        return redirect()->route('recipes.show_all');
    }

    public function show_all(){

        $recipes = Auth::user()->recipes;
        $ingredients = Ingredient::all();
        $preparations = Preparation::all();


        return view('recipes.show_all', compact('recipes', 'ingredients', 'preparations'));
    }

    public function search(Request $request){

        $search = $request->search;

        $recipes = Recipe::where('name', 'like', '%' . $search . '%')->get();
        $ingredients = Ingredient::all();


        return view('recipes.search', compact('recipes', 'ingredients'));
    }

}

resources/views/recipes/create.blade.php
@extends('layouts.app')

@include('inc.navbarUser')

@section('content')

    @include('inc.sidebar')

    <div class="col col-lg-10 mt-3">

    @if($errors->any())
        <div class="alert alert-danger mt-5">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
            <form action="{{ route('recipes.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="col-md-10">
                    <div class="card">
                        <h6 class="card-header text-muted">Nieuw recept</h6>
                        <div class="card-body">
                            <h5 class="card-title">Recepten naam</h5>
                            <input type="text" class="form-control" name="name"><br>
                            @if($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                            <div class="form-group">
                                <input type="file" name="file">
                                @if($errors->has('file'))
                                <span class="text-danger">{{ $errors->first('content') }}</span>
                                @endif

                            </div>
                            <button class="btn btn-outline-primary btn-sm" type="submit" name="submit">Create recept</button>
                        </div>


                    </div>
                </div>
                {{--<div class="form-group">--}}
                    {{--<label for="name">Recepten naam</label>--}}
                    {{--<input class="form-control" type="text" name="name">--}}
                    {{--@if($errors->has('name'))--}}
                        {{--<span class="text-danger">{{ $errors->first('name') }}</span>--}}
                    {{--@endif--}}
                {{--</div>--}}
                {{--<div class="form-group">--}}
                    {{--<input type="file" name="file">--}}
                    {{--@if($errors->has('file'))--}}
                        {{--<span class="text-danger">{{ $errors->first('content') }}</span>--}}
                    {{--@endif--}}
                {{--</div>--}}
                {{--<div class="form-group">--}}
                    {{--<input class="btn btn-primary" type="submit" name="submit" value="Next step">--}}
                {{--</div>--}}
            </form>

    </div>


    @endsection

resources/views/recipes/edit.blade.php
@extends('layouts.app')

@include('inc.navbarUser')

@section('content')

    @include('inc.sidebar')

    <div class="col col-lg-10 mt-3">

        <form action="{{ route('recipes.update', $recipe->id) }}" method="post" enctype="multipart/form-data">
            @method ('Put')
            {{ csrf_field() }}
            <div class="col-md-10">
                <div class="card">
                    <h6 class="card-header text-muted">Edit recept</h6>
                    <div class="card-body">
                        <h5 class="card-title">Recepten naam</h5>
                        <input type="text" class="form-control" value="{{ $recipe->name }}"><br>
                        <button class="btn btn-outline-primary btn-sm">Edit recept</button>
                    </div>
                </div>
            </div>
        </form>
        {{--end edit receptnaam--}}

       {{-- Add New Ingredient--}}
        <div class="col col-lg-10">
            <h3>Ingredi&euml;nten</h3>
            <table class="table table-sm table-striped">
                <thead>
                <tr>
                    <th>Ingredient</th>
                    <th>Hoeveelheid</th>
                    <th>Eenheid</th>
                    <th>Controls</th>
                </tr>
                </thead>
                <tbody>
                @foreach($quantities as $quantitie)
                    <tr>

                        <td>{{ $ingredients->where('id',$quantitie->ingredient_id)->first()['name'] }}</td>
                        <td>{{ $quantitie->quantity }}</td>
                        <td>{{ $quantitie->units }}</td>
                        <td>
                            <form action="{{route('quantity.destroy', [$recipe->id ,$quantitie->id])}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <a href="{{ route('quantity.edit' , [$recipe->id, $quantitie->id]) }}" class="btn btn-outline-secondary btn-sm">Edit</a>
                                <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="text-right">
                <a href="{{ route('quantity.create' , $recipe->id) }}" class="btn btn-sm btn-outline-secondary">Ingredi&euml;nt toevoegen</a>
            </div><br>
        </div>
        {{--    End Add Ingredient--}}

        {{--Add new Preparation--}}
        <div class="col col-lg-10">
            <h3>Bereiding</h3>
                <table class="table table-sm table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Desc</th>
                        <th>Controls</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($preparations as $preparation)
                        <tr>
                            <td>{{ $loop->count }}</td>
                            <td>{{ str_limit(strip_tags($preparation->desc))  }}</td>
                            <td >
                                <form action="{{ route('preparation.destroy', [$recipe->id, $preparation->id]) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <a href="{{ route('preparation.edit', [$recipe->id, $preparation->id]) }}" class="btn btn-outline-secondary btn-sm">Edit</a>
                                    <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            <div class="text-right">
                <a href="{{ route('preparation.create' , $recipe->id) }}" class="btn btn-sm btn-outline-secondary">Bereiding toevoegen</a>
            </div>
        </div>
        {{--    End Preparation--}}

    </div>



@endsection

resources/views/recipes/index.blade.php
@extends('layouts.user')

@section('content')

    <h1>Recepten komen hier</h1>

    <main>
        <div class="col-md-4">
            <div class="well">
                <form action="{{ route('recipes.search') }}" method="post">
                    {{ csrf_field() }}
                    <div class="input-group">
                        <input name="search" type="text" class="form-control" >
                        <span class="form-inline">
                            <button name="submit" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </span>
                    </div>
                </form>
            </div><br>
        </div>
        <div class="card-deck">
            @foreach( $recipes as $recipe)
                <div class="col-md-4">
                    <div class="card">
                        <img src="/images/{{ $recipe->photos->path }}" width="80px" alt="image" class="card-img" style="width: 328px; height: 200px;">
                        <div class="card-body">
                            <h5 class="card-title" style="min-height: 50px;">{{ $recipe->name }}</h5>
                            @foreach($recipe->preparations as $preparation)
                                {{ str_limit(strip_tags($preparation->desc)) }}
                            @endforeach
                            <p class="card-text" style="min-height: 30px;">

                            </p>
                            <a href="{{ route('recipes.show', $recipe->id) }}">Lees meer</a>
                        </div>
                    </div>
                    <br>
                </div>
            @endforeach
        </div>
        {{ $recipes->links() }}
    </main>




@endsection

resources/views/recipes/search.blade.php
@extends('layouts.user')

@section('content')
<div class="card mt-3">
    @foreach($recipes as $recipe)
        <div class="card-body">
            <h2 class="card-title">{{ $recipe->name }}</h2>
            <img src="/images/{{ $recipe->photos->path }}" width="80px" alt="image" class="card-img" style="width: 328px; height: 200px;">
            <h5 class="mt-3">Ingredi&euml;nten</h5>
            <ul>
                @foreach($recipe->quantities as $quantity)
                    <li>{{ $quantity->quantity }} {{$quantity->units}} {{ $ingredients->find($quantity->ingredient_id)->name }}</li>
                @endforeach

            </ul>
            <p class="text"></p>
            <h5>Bereiding</h5>
            <p class="card-text">
                @foreach($recipe->preparations as $preparation)
                    {!! $preparation->desc !!}
                @endforeach
            </p>
        </div>
    @endforeach
</div>
    @endsection

resources/views/recipes/show.blade.php
@extends('layouts.user')

@section('content')
    <main>
        <div class="col mt-3">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">{{ $recipe->name }}</h2>
                    <img src="/images/{{ $recipe->photos->path }}" width="80px" alt="image" class="card-img" style="width: 328px; height: 200px;">
                    <h5 class="mt-3">Ingredi&euml;nten</h5>
                    <ul>
                        @foreach($recipe->quantities as $quantity)
                            <li>{{ $quantity->quantity }} {{$quantity->units}} {{ $ingredients->find($quantity->ingredient_id)->name }}</li>
                        @endforeach

                        
                    </ul>
                    <p class="text"></p>
                    <h5>Bereiding</h5>
                    <p class="card-text">
                        @foreach($recipe->preparations as $preparation)
                            {!! $preparation->desc !!}
                        @endforeach
                    </p>
                </div>
            </div>
            <br>
            <a href="{{ route('recipes.index') }}" class="btn btn-outline-info btn-sm">Back to Overview</a>
        </div>

    </main>
@endsection

resources/views/recipes/show_all.blade.php
@extends('layouts.app')

@include('inc.navbarUser')

@section('content')

    @include('inc.sidebar')
    <div class="col col-lg-10 mt-3">
        <h4 class="card-header text-muted">Alle Recepten</h4>

                <table class="table table-sm table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Naam</th>
                        <th>Foto</th>
                        <th>hoeveelheid</th>
                        <th>Unit</th>
                        <th>Ingredienten</th>
                        <th>Bereiding</th>
                        <th width="120">Controls</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($recipes as $recipe)
                    <tr>
                        <td>{{ $recipe->id }}</td>
                        <td>{{ $recipe->name }}</td>
                        <td><img src="/images/{{ $recipe->photos->path }}" width="80px"></td>
                        <td>
                            <ul>
                                @foreach($recipe->quantities as $quantity)
                                    <li>{{$quantity->quantity}}</li>
                                @endforeach
                            </ul>
                        </td>
                        <td>
                            <ul>
                                @foreach($recipe->quantities as $quantity)
                                    <li>{{$quantity->units}}</li>
                                @endforeach
                            </ul>
                        </td>
                        <td>
                            <ul>
                            @foreach($recipe->quantities as $quantity)
                                <li>{{ $ingredients->where('id',$quantity->ingredient_id)->first()['name'] }}</li>
                            @endforeach
                            </ul>
                        </td>
                        <td>
                            @foreach($recipe->preparations as $preparation)
                                {{ str_limit(strip_tags($preparation->desc)) }}
                            @endforeach
                        </td>
                        <td>
                            <form action="{{ route('recipes.destroy', $recipe->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <a href="{{ route('recipes.edit', $recipe->id) }}" class="btn btn-outline-secondary btn-sm">Edit</a>
                                <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                            </form>

                        </td>

                    </tr>
                        @endforeach
                    </tbody>
                </table>
        </h3>
    </div>
    @endsection